### ISSUE TITLE
Adicionar Injeção do Log4j com CDI

### ISSUE THREAD

**Issue by thiagonasper** [joaoslz/acervo-emem#11]
```
@Produces
public Logger getLogger(InjectionPoint ip){
    return Logger.getLogger(ip.getMember().getDeclaringClass());
}


@Inject
private Logger logger;
```

**Comment by joaoslz** [comment]
Thiago,

Ficou muito legal usar o CDI com Log4J... bingo.

Amanhã vou fazer o commit das classes referentes ao cadastro de CDs/músicas.

2014-05-13 15:25 GMT-03:00 thiagonasper notifications@github.com:

**Comment by thiagonasper** [comment]
: )
Ah pois é verdade... faz dias que tinha olhado na apostila ai tava querendo colocar no sistema.. : )
