### ISSUE TITLE
Bug nos Dialogs e Ajax (PrimeFaces5)

### ISSUE THREAD

**Issue by thiagonasper** [joaoslz/acervo-emem#16]
Não consegue abrir os dialogs, e os links ajax não funcionam direito.
Ainda não consegui descobrir o que pode ser.

**Comment by joaoslz** [comment]
Thiago,

Neste caso, sugiro voltar para o primefaces 4.

abcs,

Em 2 de junho de 2014 19:58, thiagonasper notifications@github.com
escreveu:

**Comment by thiagonasper** [comment]
João, acho que descobri o problema dos dialogs. Vou atualizar.

https://code.google.com/p/primefaces/wiki/MigrationGuide

4.0 to 5.0

Widgets must be referenced via "PF". e.g. PF('widgetVarName').show() instead of widgetVarName.show();

**Comment by joaoslz** [comment]
blz thiago.

2014-06-03 20:45 GMT-03:00 thiagonasper notifications@github.com:
