### ISSUE TITLE
Não permitir o cadastro Duplicado de Assunto, Editora, Local, Autor, ...

### ISSUE THREAD

**Issue by joaoslz** [joaoslz/acervo-emem#17]
Validar, antes de inserir/atualizar, se um assunto, editora, autor, compositor, instrumento, gravadora já foi cadastrado.

**Comment by thiagonasper** [comment]
Implementado para as telas de cadastros auxiliares. Porém não para os dialogs auxiliares.

**Comment by thiagonasper** [comment]
Consegui! Finalmente!
Agora os dialogs utilizam o Mesmo ManagedBean da páginas de cadastros auxiliares.
Agora os dialogs utilizam a mesma validação, de nome duplicado.

Exemplo de Funcionamento:
dialogAutor cadastra no managedBean AutorBean e passa o objeto Autor cadastrado para o ObraBean em questão.
