### ISSUE TITLE
Mudanças na tela de cadastro de períodico

### ISSUE THREAD

**Issue by joaoslz** [joaoslz/acervo-emem#6]
Na tela de cadastro de periódico,  deve-se remover o campo autores e incluir o campo autores para cada artigo cadastrado... Será necessário criar uma tabela separada que podemos chamá-la de  autoresDeArtigo com relacionamento N:M com a tabela Artigo.

**Comment by thiagonasper** [comment]
João, tava pensando em aproveitar a tabela Autor que já existe, e colocar apenas um campo "ehAutorDeArtigo" boolean para dizer se é ou não autor de artigo.
o que tu acha?
